logging:
    level:
        root: info
spring:
    messages:
        basename: errors
    output:
        ansi:
            enabled: always
    datasource:
        url: jdbc:h2:tcp://localhost/~/test
        username: sa
        password:
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                show_sql: true
                format_sql: true
server:
    error:
      whitelabel:
        enabled: false
      include-exception: true
      include-message: always