# Generated by Django 3.2.6 on 2021-08-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_main', '0002_food_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='food_bad',
            fields=[
                ('fno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('sense', models.CharField(max_length=20)),
                ('good', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='food_good',
            fields=[
                ('fno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('sense', models.CharField(max_length=20)),
                ('good', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'good',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='food_data',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
