# Generated by Django 3.2.6 on 2022-01-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.TextField(blank=True, null=True)),
                ('cause', models.TextField(blank=True, null=True)),
                ('cure', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'diagnose',
                'managed': False,
            },
        ),
    ]
