DRIVER_CLASS=com.mysql.cj.jdbc.Driver
DB_USER=root
DB_CONNECTION_URL=jdbc:mysql://localhost/enrollapp?characterEncoding=utf8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
DB_PWD=tkd5957!@#